#!/bin/bash
# Author: Michael Pedrotti
# Summary: Maps classes from legacy projects to incomporte a modern auto-loading
# Result: Generate a array with key => value, witch className => classPath, into a classmap.php file
# Requires: bash-5.1.16(1)-release
# URL: https://getcomposer.org/doc/04-schema.md#classmap
# URL: https://www.php.net/manual/en/function.spl-autoload-register.php

filepath=../classmap.php;

echo 'Find classes':

echo "<?php" > $filepath
echo "/**" >> $filepath
echo " * Generated by $0" >> $filepath
echo " */" >> $filepath
echo "return array("  >> $filepath

classes=$(egrep '^(final\s+)?(abstract\s+)?class' ../classes/ -R --exclude-dir='.svn' --exclude-dir='.git' | \
	sed -r 's/(\.\.\/)//g' |  \
    sed -e 's/final[[:space:]]//g'  | \
	sed -e 's/abstract[[:space:]]//g'  | \
	sed -e 's/:class//g'  | \
	sed -e "s/[[:space:]]/|/g" |  \
	sort
);

for class in $classes; do
  
	array=(${class//|/ })
	classname=`echo ${array[1]} | sed -r "s/\W+//g"`
	
	echo -e "\t'$classname' => '${array[0]}',"  >> $filepath

	echo -e "\t- ${classname}"

done

echo "Done"
echo "Mapper at $filepath"

echo ");" >> $filepath

